name: Deploy Content to TestWkSpace [bcb0f40f-f777-4c88-aabb-e7c7e9d89afc]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-bcb0f40f-f777-4c88-aabb-e7c7e9d89afc.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ main_SentinelExport_1676508000 ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-bcb0f40f-f777-4c88-aabb-e7c7e9d89afc.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'newecotestrg2'
      workspaceName: 'TestWkSpace'
      workspaceId: 'd67b16c8-7718-48cc-bb81-6b1d47ccbc3f'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzurePPE'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bcb0f40ff7774c88aabbe7c7e9d89afc }}
      contentTypes: 'AnalyticsRule,HuntingQuery,Playbook'
      branch: 'main_SentinelExport_1676508000'
      sourceControlId: 'bcb0f40f-f777-4c88-aabb-e7c7e9d89afc'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bcb0f40ff7774c88aabbe7c7e9d89afc }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bcb0f40ff7774c88aabbe7c7e9d89afc }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bcb0f40ff7774c88aabbe7c7e9d89afc }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-bcb0f40f-f777-4c88-aabb-e7c7e9d89afc.ps1